### ISSUE TITLE
df.select(df.metadata['MAIL_DR']).show() gives error

### ISSUE THREAD

**Issue by rroyhere** [harsha2010/magellan#106]
My column metadata has Map of Mail_DR, how can I see values in each cell or row in those map? I am using scala. If I do below, i get error 
> df.select(df.metadata["MAIL_DIR"]).show()
<console>:1: error: identifier expected but string literal found.
df.select(df.metadata["MAIL_DIR"]).show()

But if I do these, I see the maps in metadata field like below:

scala> df.select(df("metadata")).show()
17/03/10 14:54:50 WARN Executor: Managed memory leak detected; size = 190266948 bytes, TID = 8
+--------------------+
|            metadata|
+--------------------+
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
|Map(MAIL_DIR ->  ...|
+--------------------+
only showing top 20 rows

**Comment by harsha2010** [comment]
try this: df.select(df.metadata("MAIL_DIR")).show()

**Comment by rroyhere** [comment]
df.select(df.metadata("MAIL_DIR")).show() -- did not help, same error but  df.select($"metadata"("MAIL_DIR")).show() worked. But I could not see any data. Output is blank like below.

Even if I don  df.select($"metadata"("MAIL_DIR")).show(2000)- some of ht erows have only one letter but most of them with no data.
- scala> df.select($"metadata"("MAIL_DIR")).show()
17/03/13 13:22:00 WARN Executor: Managed memory leak detected; size = 128514256 bytes, TID = 2
+------------------+
|metadata[MAIL_DIR]|
+------------------+
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
|                  |
+------------------+
only showing top 20 rows

**Comment by rroyhere** [comment]
Actually, I see some details if I do explode, I realize field name is not always MAIL_DIR:
Can you please advise the different commands/options to do more deeper level of explode

scala> df.select(explode($"metadata").as(Seq("k", "v"))).show(10)

+----------+--------------------+
|         k|                   v|
+----------+--------------------+
|  MAIL_DIR|                    |
| MAIL_QDRT|                    |
|APN_SEQ_NO|                   1|
| CNTY_CODE|                 075|
|MAIL_STATE|                  CA|
|       ZIP|               94132|
|  MAP_REF1|19-A3            ...|
|      APN2|                 ...|
|      CITY|SAN FRANCISCO    ...|
| OWN2_LAST|                 ...|
+----------+--------------------+
