### ISSUE TITLE
rename metadata to attributes or properties

### ISSUE THREAD

**Issue by Charmatzis** [harsha2010/magellan#139]
Hi, it would be a nice improvement if you changed the property "metadata" to "attributes" or "properties".
In the GIS world metadata are the data that describes the dataset e.g. creation date, owner etc. 

The data that follows the geometries are called "attributes"
http://support.esri.com/en/other-resources/gis-dictionary/term/attribute 
https://en.wikiversity.org/wiki/GIS/attributes 

or if you want to go as  in GeoJson specification you can call them "properties" 
https://geojson.org/geojson-spec.html#feature-objects

**Comment by harsha2010** [comment]
@Charmatzis I don't have a super strong opinion about this: technically metadata is the right word as it is describing data about a shape.
I think of property of a shape as something that is fundamental to a shape, e.g. is it convex? does it have holes? etc. 
So just semantically, metadata seems like the more appropriate word.

Also, from a practical perspective, calling this column by any other name is inexpensive.. simply rewrite the column using select($"metadata".as("properties")). This is one of the advantages of using Spark SQL, these are cheap operations.

I would however avoid calling it attributes as it is confusing (Spark SQL has column attributes which mean something different).
In any case, when you read/ write data out of Magellan this is not an issue as the readers and writers can always do the right thing.

So I agree with you that the readers and writers should do the right thing, which is how they will work.
But I don;t think we need to rename this just to match GeoJSON as long as it is intuitive what this field means.

But, if there is a strong preference in the Magellan user base to call this properties, I would be completely fine with it:  would you mind creating a PR for it and I can review and merge it in

**Comment by Charmatzis** [comment]
@harsha2010 thx mate. we will be in touch. (I will close this issue)
