### ISSUE TITLE
How to perform a left join between points and polygons?

### ISSUE THREAD

**Issue by Perados** [harsha2010/magellan#142]
I am trying to tag a DataFrame of points with metadata coming from a geojson. So it is basically a "left join". Is there a way to do this with magellan? The readme only shows an inner join (in the "within" example).
I have a workaround for this, but I was wondering if I am just reinventing the wheel here.

**Comment by harsha2010** [comment]
are you trying to join on some id column on both points and polygons and want to keep points that don't have a matching row on the right side? that would be a left outer join on the id column

Otherwise can you explain what you are doing in pseudocode or something ?

**Comment by harsha2010** [comment]
@Perados closing this, we can discuss in gitter and open an issue if there is any functionality we need to add to Magellan.
