### ISSUE TITLE
Mailing list, Slack, Gitter, etc...

### ISSUE THREAD

**Issue by Perados** [harsha2010/magellan#143]
I am asking a lot of questions as issues on GitHub, not good. Maybe we can start building a community around magellan? Are there any mailing lists, slack or gitter rooms? A gitter would be awesome.
Any other suggestions?

I am using magellan with big data sets (billions of rows every day), and I love it. I am sure there is a lot of people interested in the project.

Cheers! 🍻

**Comment by harsha2010** [comment]
i was thinking the same.. I will set up a slack channel for magellan

**Comment by harsha2010** [comment]
https://gitter.im/magellan-dev/
