### ISSUE TITLE
Contains predicate not working

### ISSUE THREAD

**Issue by nkaralis** [harsha2010/magellan#151]
Greetings,

I am trying to do a spatial join using the "contains" predicate, but i get the following exception:
`Exception in thread "main" org.apache.spark.sql.AnalysisException: cannot resolve 'contains(`polygon`, `point`)' due to data type mismatch: argument 1 requires string type, however, '`polygon`' is of polygon type. argument 2 requires string type, however, '`point`' is of point type.;;`
The code that produces the exception is:
`var resultSetCount = polygonsDf.select("polygon").join(pointsDf.select("point")).where($"polygon" contains $"point").count()`

The other two predicates ("intersects" and "within") are working as expected. 
```
ScalaVersion = "2.11.8"
SparkVersion = "2.2.0"
```

Best regards.

**Comment by harsha2010** [comment]
@nkaralis thanks, i should document contains actually... but you cannot use contains the way you have it right now since it does a string contains check (contains is actually a Spark SQL expression)
so Magellan uses a special operator for contains:

 val sqlCtx = this.sqlContext
    import sqlCtx.implicits._
    val ring = Array(Point(1.0, 1.0), Point(1.0, -1.0),
      Point(-1.0, -1.0), Point(-1.0, 1.0),
      Point(1.0, 1.0))
    val polygons = sc.parallelize(Seq(
      PolygonExample(Polygon(Array(0), ring))
    )).toDF()

    val points = sc.parallelize(Seq(
      PointExample(Point(0.0, 0.0)),
      PointExample(Point(2.0, 2.0))
    )).toDF()

    val joined = points.join(polygons).where($"polygon" >? $"point") // the operator >? = contains in Magellan

can you try this out and see if it works?

**Comment by nkaralis** [comment]
@harsha2010 Yes, it works! Thanks for helping me out!
