### ISSUE TITLE
Maven Coordinates for SprakCloudera 2

### ISSUE THREAD

**Issue by khajaasmath786** [harsha2010/magellan#158]
Hi,

we are using cloudera version of spark2. What will be the maven co-ordinates for magellan for this version of spark.

    <scala.version>2.11.8</scala.version>
    <scala.compat.version>2.11.8</scala.compat.version>
    <scala.binary.version>2.11</scala.binary.version>
    <spark.version>2.0.0.cloudera2</spark.version>
    <hadoop.version>2.6.0-cdh5.10.0</hadoop.version>
    <hiveJDBCVersion>1.1.0-cdh5.10.0</hiveJDBCVersion>
    <hbase.version>1.2.0-cdh5.10.0</hbase.version>

Thanks,
Asmath

**Comment by harsha2010** [comment]
<dependency>
<groupId>harsha2010</groupId>
<artifactId>magellan</artifactId>
<version>1.0.5-s_2.11</version>
<type>jar</type>

you will need to add the spark jars separately to the pom
