### ISSUE TITLE
Slope for lines that are parallel to the Y axis

### ISSUE THREAD

**Issue by Charmatzis** [harsha2010/magellan#172]
https://github.com/harsha2010/magellan/blob/134bd156b1fba5999cfba89461533442028ffe9d/src/main/scala/magellan/geometry/R2Loop.scala#L82

Since you divine with the x difference of the two points, if that is 0 , we have problem.....

**Comment by harsha2010** [comment]
actually that's not true... if the point.x is outside the start.x/end.x then cond1 and cond2 will be false... otherwise true(a ray does intersect a edge that it is parallel to and shares a point with
Would be good to check by writing a unit test

**Comment by harsha2010** [comment]
@Charmatzis look at #173 , it exhibits tests for these scenarios and shows it works just fine
