### ISSUE TITLE
Points falling under multiple polygons - Index 15

### ISSUE THREAD

**Issue by khajaasmath786** [harsha2010/magellan#185]
Here is the result dataset that we got after running the program with index 15.

Our polygons are dealer locations in usa and point can be any event occured on the road spread across usa. so we need to check if the 

vin,utctime,latitude,longitude,geotext,zoneid,name
1XPBD49X2GD325643,8/1/2017 13:12,38.6915855,-112.150192,"POLYGON ((-104.041 45.027, -111.028 45.027, -111.094 42.0167, -120.015 42.0003, -120.015 39.4192, -123.772 38.7369, -119.443 32.4912, -114.939 32.6394, -110.984 31.2598, -109.028 31.2973, -109.006 36.2088, -107.864 36.2088, -107.886 37.0026, -102.019 36.985, -102.019 40.9799, -104.041 41.0131, -104.041 45.027))",4079,PDC - Las Vegas
1XPBD49X2GD325643,8/1/2017 13:12,38.6915855,-112.150192,"POLYGON ((-126.475 48.8936, -122.827 33.4681, -108.545 30.6379, -107.93 48.9225, -126.475 48.8936))",4115,Western US
1XPBD49X2GD325643,8/1/2017 13:12,38.6915855,-112.150192,"POLYGON ((-126.387 48.691, -120.85 22.7559, -78.8379 24.6071, -63.8086 48.2247, -126.387 48.691))",4235,ENTIRE US
1XPBD49X2GD325643,8/1/2017 13:12,38.6915855,-112.150192,"POLYGON ((-127.969 48.691, -120.234 25.7999, -74.9707 25.0856, -65.8301 50.0642, -129.375 50.5134, -127.969 48.691))",4294,USA
1XPBD49X2GD325643,8/1/2017 13:12,38.6915855,-112.150192,"POLYGON ((-120.849 37.4699, -120.851 37.4699, -120.851 37.4699, -120.851 37.4691, -120.849 37.4695, -101.883 20.6328, -79.6641 28.7985, -68.6953 45.4848, -98.2266 48.1778, -108.633 48.1778, -123.539 48.7374, -120.849 37.4699))",4461,DTL Logistics Inc 
1XPBD49X2GD325643,8/1/2017 13:12,38.6915855,-112.150192,"POLYGON ((-68.4002 44.2718, -123.574 48.1074, -121.641 30.1451, -80.332 24.2069, -68.4002 44.2718))",4537,48 States
1XPBD49X2GD325643,8/1/2017 13:12,38.6915855,-112.150192,"POLYGON ((-97.3866 25.8892, -80.5322 25.2646, -65.2172 46.3621, -104.199 48.8936, -124.458 49.1817, -124.15 41.9677, -106.352 31.5411, -97.3866 25.8892))",81079,TCI 99
1XPBD49X2GD325643,8/1/2017 13:12,38.6915855,-112.150192,"POLYGON ((-97.3866 25.8892, -80.5322 25.2646, -65.2172 46.3621, -104.199 48.8936, -124.458 49.1817, -124.15 41.9677, -106.352 31.5411, -97.3866 25.8892))",81080,TCI 99
1XPBD49X2GD325643,8/1/2017 13:12,38.6915855,-112.150192,"POLYGON ((-124.805 49.0091, -124.189 40.246, -120.059 32.4356, -103.096 31.9894, -104.106 49.0091, -124.805 49.0091))",81120,West Coast
1XPBD49X2GD325643,8/1/2017 13:12,38.6915855,-112.150192,"POLYGON ((-118.244 31.9324, -107.358 31.1846, -106.655 52.4292, -127.793 52.5363, -124.255 39.6057, -118.244 31.9324))",81615,West Region
1XPBD49X2GD325643,8/1/2017 13:12,38.6915855,-112.150192,"POLYGON ((-119.971 48.8069, -124.277 48.5166, -123.926 40.4469, -121.553 36.3859, -117.07 32.5468, -108.896 31.3912, -106.567 37.3352, -113.994 48.72, -119.927 48.7489, -119.971 48.8069))",81786,Alans Zone
1XPBD49X2GD325643,8/1/2017 13:12,38.6915855,-112.150192,"POLYGON ((-128.057 49.2678, -122.256 29.6881, -71.4551 29.6881, -59.6777 49.153, -128.057 49.2678))",81876,blue water
1XPBD49X2GD325643,8/1/2017 13:12,38.6915855,-112.150192,"POLYGON ((-113.574 36.1329, -109.092 36.9449, -101.973 36.9098, -102.105 40.8756, -103.863 41.0747, -104.013 45.1419, -104.145 49.0173, -117.153 49.0749, -117.661 45.9774, -117.705 44.5511, -118.577 41.7682, -118.357 40.2764, -117.61 39.0927, -115.72 37.8195, -115.149 36.8763, -114.497 34.5919, -113.574 36.1329))",81886,USWEST - DMN

**Comment by harsha2010** [comment]
@khajaasmath786 can you double check the data?
I checked with ESRI Java API and it returns the same values as Magellan for this dataset.
I think one or more points might have an error in their measurement so its likely the polygons are covering a larger area than expected and in particular intersecting.
