### ISSUE TITLE
Missing coordinates

### ISSUE THREAD

**Issue by mithdrann** [harsha2010/magellan#187]
Hi, I'm trying to link the project but the coordinates provided by README.md seem to be missing:

groupId: harsha2010
artifactId: magellan
version: 1.0.5-s_2.11

Could you check it?

**Comment by CharmLynn** [comment]
which project? plz give the project url




At 2017-12-04 20:17:33, "mithdrann" <notifications@github.com> wrote:


Hi, I'm trying to link the project but the coordinates provided by README.md seem to be missing:

groupId: harsha2010
artifactId: magellan
version: 1.0.5-s_2.11

Could you check it?

**Comment by mithdrann** [comment]
Hi, maybe I didn't explain myself in a proper way. I mean, I cannot link against the latest release of Magellan (https://github.com/harsha2010/magellan) using the coordinates within README.md

**Comment by mithdrann** [comment]
Solved. As stated in issue #103, Magellan is not available as a maven package yet,  only as a spark package. Adding the following repository to the pom.xml solves the problem.

<repository>
    <id>SparkPackagesRepo</id>
    <url>http://dl.bintray.com/spark-packages/maven</url>
 </repository>
