### ISSUE TITLE
Ensure examples in README and Wiki actually run

### ISSUE THREAD

**Issue by andrewor14** [harsha2010/magellan#19]

**Comment by harsha2010** [comment]
+1, thanks!

**Comment by kentore82** [comment]
Im having datatype issues with the pyspark examples:
> $SPARK_HOME/bin/pyspark --packages harsha2010:magellan:1.0.3-s_2.10

    from magellan.types import Point, Polygon
    from pyspark.sql import Row, SQLContext
    print('Spark v. '+sc.version)

    PointRecord = Row("id", "point")

    points = sc.parallelize([
    (0, Point(-1.0, -1.0)),
    (1, Point(-1.0, 1.0)),
    (2, Point(1.0, -1.0))])\
    .map(lambda x: PointRecord(*x)).toDF()

    points.show()

    Spark v. 1.4.1
    ---------------------------------------------------------------------------
    ...
    /hadoop-dist/spark/python/pyspark/sql/types.pyc in _verify_type(obj, dataType)
    1008 
    1009     _type = type(dataType)
    -> 1010     assert _type in _acceptable_types, "unknown datatype: %s" % dataType
    1011 
    1012     # subclass of them can not be deserialized in JVM
    
    AssertionError: unknown datatype: Point (0.0,0.0)

**Comment by sto-nith** [comment]
Hi,

I am facing the same issue with pyspark 1.4

           AssertionError: unknown datatype: Point (0.0,0.0)

Anyone found the resolution yet?
