### ISSUE TITLE
View base32 index values in the dataframe? 

### ISSUE THREAD

**Issue by jim2** [harsha2010/magellan#193]
Hi - is there a way to view the base32 geohash values in the dataframe?  

In my index column I see "[[ZOrderCurve(-71.3671875, 44.296875, -71.015625, 44.47265625, 20, 7347376501450342400, 01100101111101110010),Intersects], [ZOrderCurve(-71..."

But I would like to be able to output the geohash values that make up the geometry. (i.e. "dqcj" for geohash 4)  Is that possible? 

Thanks!
Jim

scala> statesidx.show(10)
+-----+--------+--------------------+--------------------+-----+--------------------+
|point|polyline|             polygon|            metadata|valid|               index|
+-----+--------+--------------------+--------------------+-----+--------------------+
| null|    null|magellan.Polygon@...|Map(STATE_ABBR ->...| true|[[ZOrderCurve(-80...|
| null|    null|magellan.Polygon@...|Map(STATE_ABBR ->...| true|[[ZOrderCurve(-83...|
| null|    null|magellan.Polygon@...|Map(STATE_ABBR ->...| true|[[ZOrderCurve(-12...|
| null|    null|magellan.Polygon@...|Map(STATE_ABBR ->...| true|[[ZOrderCurve(-90...|
| null|    null|magellan.Polygon@...|Map(STATE_ABBR ->...| true|[[ZOrderCurve(-72...|
| null|    null|magellan.Polygon@...|Map(STATE_ABBR ->...| true|[[ZOrderCurve(-10...|
| null|    null|magellan.Polygon@...|Map(STATE_ABBR ->...| true|[[ZOrderCurve(-93...|
| null|    null|magellan.Polygon@...|Map(STATE_ABBR ->...| true|[[ZOrderCurve(-10...|
| null|    null|magellan.Polygon@...|Map(STATE_ABBR ->...| true|[[ZOrderCurve(-16...|
| null|    null|magellan.Polygon@...|Map(STATE_ABBR ->...| true|[[ZOrderCurve(-71...|
+-----+--------+--------------------+--------------------+-----+--------------------+

**Comment by jim2** [comment]
solved this using base32 function

**Comment by IsamAljawarneh** [comment]
Hi jim2, 
can you mention how could you use base32 function to solve this problem.
i am also interested in the same scenario.
Thanks a lot.

**Comment by FioriniRiccardo** [comment]
Hello jim2,
I am interested in your solution too. I would be grateful if you could post it.
Thanks in advance!

**Comment by harsha2010** [comment]
hey!
A ZOrderCurve has a function called .toBase32() that returns the geo hash string (which is nothing but a base 32 encoded string).
So all you'd need to do is write a UDF that does something like
geohashUDF = udf{(curve: Seq[ZOrderCurve]) => curve.map(_.toBase32())} and use it as:
df.withColumn("geohashes", geohashUDF($"index.curve"))

I haven't tested the above syntax but morally it should do the right thing...

**Comment by FioriniRiccardo** [comment]
Thanks a lot! I will test it!
