### ISSUE TITLE
Cannot import magellan.Point in pyspark

### ISSUE THREAD

**Issue by andrewor14** [harsha2010/magellan#20]
I ran magellan with the pyspark shell as the [wiki](https://github.com/harsha2010/magellan/wiki/Python-API) instructs:
```
bin/pyspark --packages harsha2010:magellan:1.0.1-s_2.10
```
then ran into
```
>>> from magellan.types import Point, Polygon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rsriharsha/projects/hortonworks/spatialsdk/python/magellan/types.py", line 19, in <module>
    BooleanType = bool
ImportError: No module named shapely.geometry
```
Looks like the python path is hardcoded somewhere?

**Comment by harsha2010** [comment]
Ah , I forgot I require shapely to be present in Python path on the Python API... Will need to make this optional and only required when types are converted to shapely types

**Comment by harsha2010** [comment]
this has been fixed. we are no longer using Shapely as of 1.0.3
