### ISSUE TITLE
PySpark examples

### ISSUE THREAD

**Issue by Tagar** [harsha2010/magellan#205]
That's an awesome product. 
Was great to see presentation last week on Strata Data Conference. 

Could you please point me to some PySpark examples using Magellan? 
Thank you !

**Comment by harsha2010** [comment]
@Tagar the Python API will be available once #210 is done. It was broken in 1.0.5 due to some Spark 1.6+ incompatibilities which need to be resolved

**Comment by Tagar** [comment]
Good to know. Thanks @harsha2010
