### ISSUE TITLE
WKT parser problem

### ISSUE THREAD

**Issue by geoHeil** [harsha2010/magellan#226]
the WKT parser fails with `Caused by: java.lang.RuntimeException: Extra(... 48.3118488844536))), [traced - not evaluated])`
however, regular JTS parser seems to work fine.

**Comment by harsha2010** [comment]
can you attach an example where the parser fails?

**Comment by geoHeil** [comment]
I have contacted you with an example

**Comment by harsha2010** [comment]
@geoHeil looks like this is because of extra quotes "" .. you can strip the extra quotes before passing it to Magellan via StringEscapeUtils.unescapeCsv(line) or stripPrefix/stripSuffix

**Comment by harsha2010** [comment]
spark.read.parquet("...")
.filter(! ($"indoor_geo" contains "MULTIPOLYGON"))
.withColumn("polygon", wkt($"indoor_geo")("polygon")).collect()

Looks like this file has a mix of polygon and multi polygon. We don't yet support multi polygons. Thats why this is failing I think
