### ISSUE TITLE
JDBC connection to PostGIS throws *unsupportedType*

### ISSUE THREAD

**Issue by Elbehery** [harsha2010/magellan#31]
SparkSQL JDBC connection fails to retrieve a table with **Geometry** type. Please consider the following scenario :

I have a Database named "nycesri" in my postgres, with GIS Extension. It contains two tables, one with only *primitive types* named **spatial_ref_sys**, the other table named **ny_counties_clip** has a field of *Geometry* type. 

I have launched spark_shell with **PostgresJDBC.jar** in the classPath with the following command :

**SPARK_CLASSPATH=/home/mustafa/Desktop/postgresql-9.3-1104.jdbc41.jar ./spark-shell**

Then, I have loaded the first table successfully into a SparkDF using the following query :

*val jdbcDF = sqlContext.read.format("jdbc").options(
  Map("url" -> "jdbc:postgresql:nycesri",
  "dbtable" -> "spatial_ref_sys")).load()*

**However**, when I have tried to load the other table, which contains the Geometry type using the following query :

*val jdbcDF = sqlContext.read.format("jdbc").options(
    Map("url" -> "jdbc:postgresql:nycesri",
    "dbtable" -> "ny_counties_clip")).load()*

I have received **java.sql.SQLException: Unsupported type 1111**
![selection_008](https://cloud.githubusercontent.com/assets/2375289/11061692/1897b938-87a9-11e5-9633-2c317e9235f5.png)

**Comment by harsha2010** [comment]
@Elbehery , thanks for opening this ticket. I hadn't looked into the JDBC side yet, thanks for catching this issue.

**Comment by harsha2010** [comment]
@Elbehery I'm closing this issue as this is not Magellan related. Please post to Spark SQL , the problem lies in reading PostGIS data types via JDBC. I am opening a separate ticket to investigate if Magellan has any issues with JDBC

**Comment by Elbehery** [comment]
@harsha2010  I have already tried to open a ticket on Spark SQL before opening this issue. Though, spark team closed the bug, as they said it is not spark related issue !!.. U can find the ticket here https://issues.apache.org/jira/browse/SPARK-11526

**Comment by harsha2010** [comment]
Hi Mustafa

I looked at the ticket, per Sean's comments, it is not clear this is a
Spark SQL issue. As he points out, the return type is not supported in
Spark SQL since Spark SQL does not know about Geometry type... there are
only two ways i think to solve this, one is to write your own extensions to
Spark SQL to deal with these sort of types (wrapping custom types), or use
Magellan.
I don't think Spark will automatically solve this for you and this is not
really a bug in Spark as far as I can see

Ram
