### ISSUE TITLE
read.format("magellan") throws scala.NotImplementedError: an implementation is missing

### ISSUE THREAD

**Issue by Elbehery** [harsha2010/magellan#48]
I have tried to load many shape files for NYC .. Although some the of the files worked fine, other threw **scala.NotImplementedError: an implementation is missing** .. I loaded the same files into PostGIS, and it worked fine. So, I am sure the files are not corrupted. 

Would like to know the cause of the problem, and to solve the issue if possible.
![selection_006](https://cloud.githubusercontent.com/assets/2375289/12596944/ed147eba-c482-11e5-9e01-edf92f4b48a7.png)

**Comment by harsha2010** [comment]
@Elbehery thanks for raising the issue. Can you please attach one of the files we are not able to load to this issue and i will take a look

**Comment by Elbehery** [comment]
@harsha2010  , attached

[NY_counties_clip.zip](https://github.com/harsha2010/magellan/files/106347/NY_counties_clip.zip)
[nyc-homicides.zip](https://github.com/harsha2010/magellan/files/106348/nyc-homicides.zip)

**Comment by qthurier** [comment]
@Elbehery , @harsha2010, did you investigate that issue? I got the same exception with most of the esri files provided by stats new zealand http://www.stats.govt.nz/browse_for_stats/Maps_and_geography/Geographic-areas/digital-boundary-files.aspx

**Comment by russel-m** [comment]
I believe this is due to the master branch not supporting floating point values in the DBReader. @simonellistonball has an open pull request (#28) with that support added, but it has not been merged in yet to my knowledge.
