### ISSUE TITLE
NAD83 UTM ZONE 18N Transformer

### ISSUE THREAD

**Issue by Elbehery** [harsha2010/magellan#49]
I am working with data from NYC, the shape file was projected using the followin system :

PROJCS["NAD83 / UTM zone 18N",
    GEOGCS["NAD83",
        DATUM["North_American_Datum_1983",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            AUTHORITY["EPSG","6269"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.01745329251994328,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4269"]],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",-75],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    AUTHORITY["EPSG","26918"],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH]]

I do not know how to transform GPS coordinates to this Datum, 

Anyone can help me with this, or at least give me direction how to implement it ?

**Comment by fragrant** [comment]
I have the same problem. I am working with data from Florida, the The coordinate system of this shape file is NAD_1983_UTM_Zone_17N. 

Anyone knows how to transform GPS coordinates to this NAD83, Zone17?

Thanks in advance!
