### ISSUE TITLE
Multi-polygon support

### ISSUE THREAD

**Issue by INRIX-Trang-Nguyen** [harsha2010/magellan#55]
Hi Ram,

I know this has been raised for

**Comment by INRIX-Trang-Nguyen** [comment]
Hi Ram,

I know this has been raised before, but I need to join a table container 25 million trip records to a geography table whose geometries are multi-polygons and metadata about the country and states. Currently since multi-polygons are not first class udfs. I'm wondering what would be the most efficient way to handle a join that would aggregate trip counts by geography name using the "$"start_point" within $"polygon"" predicate.

Currently, I've created a dataframe that contains a Seq[Polygons]:
case class Geography(geography_id: String,
                       geography_name: String,
                       geography_type: String,
                       region: String,
                       polygons: Seq[Polygon]
                   )

In postgis, this looks like:

select date_trunc('hour', startts) AS hour, g.region, g.type, g.name, t.provider_id, count(trip_id), 
                from trips t, map.geography g where  st_intersects(t.startloc, g.geom)
                group by 1, 2, 3, 4, 5 

Not sure how best to handle this in spark where g.geom is a multi-polygon.
Also is there a spatial index that is created on the smaller table (in this case geom), to make the query more efficient?

Thanks,
Trang

**Comment by Perados** [comment]
👍

**Comment by halfabrane** [comment]
done! We have support for multipolygons now in #123
