### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by mses-bly** [harsha2010/magellan#56]
Hi all, 

I was wondering if the project was still being maintained, since last commit was 2/3 months old and there are outstanding PRs.

Thank you

**Comment by velvia** [comment]
Along the same lines, is spatial join currently supported?  If not, what are the plans for it?

**Comment by harsha2010** [comment]
hey @mses-bly , yes the project is being maintained, we are currently working on upgrading to Spark 1.6 but running into some issues which is requiring us to rewrite some key algorithms in Magellan for efficiency purposes. We would likely need to wait until Spark 2.0 to do this efficiently. This is the reason why there is a delay

@velvia , spatial join will have to wait until the upgrade to Spark 1.6 or Spark 2.0 happens.
Once the Spark upgrade occurs we expect the APIs will be more stable and we can start accelerating on new features in Magellan

**Comment by sabman** [comment]
Thanks @harsha2010 I am wondering where I should track the development of the project. It seems all the work is being done here halfabrane/magellan but all the issues are harsha2010/magellan and you seem to have two github accounts too (@halfabrane) I think it would help from the PoV of open source contributions to have a clear working repo.

**Comment by harsha2010** [comment]
Hey @sabman , the main repo for magellan is harsha2010/magellan. This is also the repo linked in the Spark Packages.

**Comment by sabman** [comment]
@harsha2010 can cut a beta release for the Spark 1.6  branch so that it can easily be used on databricks?

**Comment by sabman** [comment]
@harsha2010 sorry I meant Spark 1.5 release. 

I'd really like to try the Python API on databricks cluster but am having trouble figuring out how to load the python packages. I have scala version working fine using the JAR upload capabilities of databricks
