### ISSUE TITLE
Anyway of converting an GEOJSON Polygon into magellan Polygon ? 

### ISSUE THREAD

**Issue by jomach** [harsha2010/magellan#57]
Hi guys, 

Anyway of converting an GEOJSON Polygon into magellan Polygon ? 
an Example would be nice. For Example I have dataframe and one of the columns is a GEOJSON Polygon. 

How can I create a Polygon with your library  ?

**Comment by harsha2010** [comment]
geojson is supported (use .option("type", "geojson") when loading data into magellan)
