### ISSUE TITLE
Can magellan support Spark2.0?

### ISSUE THREAD

**Issue by mengqingyun** [harsha2010/magellan#76]
I have tried magellan running with Spark 2.0.It seems that it will get something wrong like UnsafeRow.
Is it expected ? or I didn't use magellan correctly?

**Comment by lagerspetz** [comment]
Magellan uses UDT's and currently there seems to be no replacement for them in Spark 2.0:
http://stackoverflow.com/questions/39096268/how-to-use-user-defined-types-in-spark-2-0
So to make Magellan work on Spark 2.0, UDTs need to be replaced with something in Magellan, or implemented for Spark 2.0+.

**Comment by harsha2010** [comment]
done. UDTs are supported in Spark 2.0+ as well
