### ISSUE TITLE
using udfs with magellan

### ISSUE THREAD

**Issue by Liorba** [harsha2010/magellan#88]
Im trying to create the simplest udf to transform lat,long values to magellan point

I tried something like this:
import magellan.{Point, PointUDT, Polygon}
import org.apache.spark.sql.functions.udf
val toPointUDF = udf{(x:Double,y:Double) => new PointUDT.serialize(Point(x,y)) }

unfortunately it not pass compelation...
is this possible to do so?

**Comment by harsha2010** [comment]
what is the issue you are running into? can you attach a stack trace?

**Comment by Liorba** [comment]
I have 2 tables in Mysql 
1. A table with polygons in WKT format
2. A table with lat and long values

I wanted to read them into spark dataframe transform the polygons and and the lat/long values into magellan Polygon and Point and run an intersect join on them
all the examples I saw in the doc showed only how to read from geoJson/ESRI formats

can you share a code snippet on how can it be done?

Thanks

**Comment by harsha2010** [comment]
@Liorba  we don;t support WKT format yet. I'll follow up on this in the other ticket #87 
For the UDF issue, my question is, what error do you run into when you create a UDF the way you did above?

**Comment by Liorba** [comment]
when using version 1.04-s_2.11 on spark 2.1
PointUDT is not needed and this was my mistake

this works:

```
val toPointUDF = udf{(x:Double,y:Double) => Point(x,y) }
val df = Seq((34.44434,15.3453),(22.33,55.666)).toDF
val new_df = df.withColumn("point",toPointUDF(col("_1"),col("_2")))
new_df.show()
+--------+-------+--------------------+
|      _1|     _2|               point|
+--------+-------+--------------------+
|34.44434|15.3453|Point(34.44434, 1...|
|   22.33| 55.666|Point(22.33, 55.666)|
+--------+-------+--------------------+
```

**Comment by harsha2010** [comment]
awesome! thanks! I need to update the docs as they have become somewhat outdated. will do so asap

**Comment by sto-nith** [comment]
Hi,

I am trying to replicate the same code mentioned above in pyspark

SPARK version: 2.1.1
Magellan : 1.0.4-s_2.11
Spark catalyst: spark-catalyst_2.11-2.1.1.jar

**from magellan.types import Point, Polygon
from pyspark.sql import Row, SQLContext
from pyspark.sql.functions import *

PointRecord = Row("lon", "lat")
toPointUDF = udf(lambda x,y: Point(x,y))
df = sc.parallelize([
  (-1.0, 1.0),
  (-1.0, 1.0),
  (1.0, -1.0)])\
.map(lambda x: PointRecord(*x))\
.toDF()

new_df = df.withColumn('point', toPointUDF(df.lon, df.lat))**

But, on doing new_df.show(), it is throwing the below error.

**net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for magellan.types.Point)**

Actually, I was working on a different dataset(uber) and I was trying to read that dataset in pyspark datausing using:

**from pyspark import SparkConf,SparkContext
from magellan.types import Point, Polygon
from pyspark.sql import Row, SQLContext
from pyspark.sql.functions import *
from pyspark.sql.types import StringType, DoubleType

uberRidesDf = (
    sc
    .textFile('/home/saurabh/Downloads/uber-rides.tsv')
    .map(lambda x: x.split('\t'))
    .map(lambda x: (x[0], x[1], Point(float(x[3]), float(x[2]))))
    .toDF(['tripId', 'timestamp', 'point'])
    )**

And, it was failing while trying to convert from RDD to dataframe in the last line with below error:

**java.lang.ClassNotFoundException: magellan.PointUDT**

I cannot find any resolution to any of the above issues on any forums yet. Can anyone help with this?
