### ISSUE TITLE
toDS functions does not work with Point type

### ISSUE THREAD

**Issue by Liorba** [harsha2010/magellan#93]
I'm trying to do the following (spark 2.1.0,scala 2.11,magellan 1.0.4-s):

```
import magellan.{Point, Polygon, PolyLine}
import magellan.coord.NAD83
import org.apache.spark.sql.magellan.dsl.expressions._
import org.apache.spark.sql.Row
import org.apache.spark.sql.types._

import spark.implicits._
val ds = Seq(Point(51.5033640,-0.1276250)).toDs
```

I'm getting the following error:
`error: value toDs is not a member of Seq[magellan.Point]`

**Comment by harsha2010** [comment]
Magellan doesn't support encoders for datasets yet. Do you need to use Datasets instead of Dataframes? I will create an issue to make Magellan work with Datasets and we can track it there

**Comment by harsha2010** [comment]
tracking this here: #94
